/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/students/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить профиль текущего студента */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Профиль текущего студента */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список студентов */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                    /** @description Фильтр по email */
                    email?: components["parameters"]["StudentEmailFilter"];
                    /** @description Фильтр по имени */
                    first_name?: components["parameters"]["StudentFirstNameFilter"];
                    /** @description Фильтр по фамилии */
                    last_name?: components["parameters"]["StudentLastNameFilter"];
                    /** @description Фильтр по навыкам */
                    skills?: components["parameters"]["StudentSkillsFilter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список студентов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о студенте */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о студенте */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить данные студента */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["StudentUpdateBody"];
            responses: {
                /** @description Данные студента обновлены */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить студента */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Студент удален */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список проектов */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                    /** @description Фильтр по названию проекта */
                    name?: components["parameters"]["ProjectNameFilter"];
                    /** @description Фильтр по ID владельца проекта */
                    owner_student_id?: components["parameters"]["ProjectOwnerStudentIdFilter"];
                    /** @description Нижняя граница даты создания проекта */
                    created_from?: components["parameters"]["ProjectCreatedFromFilter"];
                    /** @description Верхняя граница даты создания проекта */
                    created_to?: components["parameters"]["ProjectCreatedToFilter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список проектов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Создать проект */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["ProjectCreateBody"];
            responses: {
                /** @description Проект создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вступить в проект */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["ProjectJoinBody"];
            responses: {
                /** @description Студент добавлен в проект */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMemberResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о проекте */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о проекте */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить проект */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["ProjectUpdateBody"];
            responses: {
                /** @description Проект обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить проект */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Проект удален */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список участников проекта */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                    /** @description Фильтр по ID студента */
                    student_id?: components["parameters"]["ProjectMemberStudentIdFilter"];
                    /** @description Фильтр по роли участника проекта */
                    role?: components["parameters"]["ProjectMemberRoleFilter"];
                    /** @description Фильтр по активности участника проекта */
                    is_active?: components["parameters"]["ProjectMemberIsActiveFilter"];
                    /** @description Нижняя граница даты вступления в проект */
                    join_date_from?: components["parameters"]["ProjectMemberJoinDateFromFilter"];
                    /** @description Верхняя граница даты вступления в проект */
                    join_date_to?: components["parameters"]["ProjectMemberJoinDateToFilter"];
                };
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список участников проекта */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMemberListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Добавить участника в проект */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["ProjectMemberCreateByProjectBody"];
            responses: {
                /** @description Участник добавлен в проект */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMemberResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию об участнике проекта */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация об участнике проекта */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMemberResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить данные участника проекта */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["ProjectMemberUpdateByProjectBody"];
            responses: {
                /** @description Данные участника проекта обновлены */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectMemberResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить участника из проекта */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Участник удален из проекта */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список команд проекта */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список команд проекта */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Создать команду внутри проекта */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["TeamCreateByProjectBody"];
            responses: {
                /** @description Команда создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о команде проекта */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о команде */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить команду проекта */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["TeamUpdateBody"];
            responses: {
                /** @description Команда обновлена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить команду из проекта */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Команда удалена */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список участников конкретной команды */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список участников команды */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMembershipListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Добавить участника проекта в команду */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["TeamMembershipCreateByTeamBody"];
            responses: {
                /** @description Участник добавлен в команду */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMembershipResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/teams/{team_id}/members/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить позицию участника в команде */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["TeamMembershipUpdateBody"];
            responses: {
                /** @description Позиция участника обновлена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMembershipResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить участника из команды */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID команды */
                    team_id: components["parameters"]["TeamId"];
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Участник удален из команды */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список спринтов проекта */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список спринтов проекта */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprintListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Создать спринт проекта */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SprintCreateRequest"];
                };
            };
            responses: {
                /** @description Спринт создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprintResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список задач проекта */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список задач проекта */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectTaskListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Создать задачу проекта */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectTaskCreateRequest"];
                };
            };
            responses: {
                /** @description Задача создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectTaskResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks/{task_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить назначения задачи */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Назначения задачи */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskAssignmentResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Назначить задачу участнику */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskAssignmentCreateRequest"];
                };
            };
            responses: {
                /** @description Задача назначена */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskAssignmentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/busy-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить слоты занятости студента */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: components["parameters"]["Page"];
                    /** @description Количество элементов на странице */
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список слотов занятости */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusySlotResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Создать слот занятости */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusySlotCreateRequest"];
                };
            };
            responses: {
                /** @description Слот занятости создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusySlotResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список запросов на изменение задач */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список запросов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskChangeRequestResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks/{task_id}/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать запрос на изменение задачи */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskChangeRequestCreateRequest"];
                };
            };
            responses: {
                /** @description Запрос создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskChangeRequestResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/sprints/{sprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о спринте */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID спринта */
                    sprint_id: components["parameters"]["SprintId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о спринте */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprintResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить спринт */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID спринта */
                    sprint_id: components["parameters"]["SprintId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SprintCreateRequest"];
                };
            };
            responses: {
                /** @description Спринт обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SprintResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить спринт */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID спринта */
                    sprint_id: components["parameters"]["SprintId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Спринт удален */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о задаче */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о задаче */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectTaskResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить задачу проекта */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectTaskCreateRequest"];
                };
            };
            responses: {
                /** @description Задача обновлена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectTaskResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить задачу проекта */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Задача удалена */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks/{task_id}/assignments/{project_member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить назначение задачи участнику */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                    /** @description ID участника проекта */
                    project_member_id: components["parameters"]["ProjectMemberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Назначение задачи */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskAssignmentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить назначение задачи */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                    /** @description ID участника проекта */
                    project_member_id: components["parameters"]["ProjectMemberId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskAssignmentCreateRequest"];
                };
            };
            responses: {
                /** @description Назначение обновлено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskAssignmentResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить назначение задачи */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID задачи */
                    task_id: components["parameters"]["TaskId"];
                    /** @description ID участника проекта */
                    project_member_id: components["parameters"]["ProjectMemberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Назначение удалено */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/busy-slots/{busy_slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о слоте занятости */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                    /** @description ID слота занятости */
                    busy_slot_id: components["parameters"]["BusySlotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о слоте занятости */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusySlotResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить слот занятости */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                    /** @description ID слота занятости */
                    busy_slot_id: components["parameters"]["BusySlotId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusySlotCreateRequest"];
                };
            };
            responses: {
                /** @description Слот занятости обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusySlotResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить слот занятости */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID студента */
                    student_id: components["parameters"]["StudentId"];
                    /** @description ID слота занятости */
                    busy_slot_id: components["parameters"]["BusySlotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Слот занятости удален */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/change-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о запросе на изменение задачи */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID запроса на изменение задачи */
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о запросе */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskChangeRequestResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Обновить запрос на изменение задачи */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID запроса на изменение задачи */
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskChangeRequestCreateRequest"];
                };
            };
            responses: {
                /** @description Запрос обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskChangeRequestResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Удалить запрос на изменение задачи */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID проекта */
                    project_id: components["parameters"]["ProjectId"];
                    /** @description ID запроса на изменение задачи */
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Запрос удален */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Статус задачи
         * @enum {string}
         */
        TaskStatus: "unassigned" | "assigned" | "in_progress" | "done";
        StudentResponse: {
            /**
             * @description Уникальный идентификатор студента
             * @example 1
             */
            id: number;
            /**
             * Format: email
             * @description Email студента
             * @example student@example.com
             */
            email: string;
            /**
             * @description Имя студента
             * @example Иван
             */
            first_name: string;
            /**
             * @description Фамилия студента
             * @example Иванов
             */
            last_name: string;
            /**
             * Format: date-time
             * @description Дата регистрации
             * @example 2026-03-13T10:00:00Z
             */
            registered_at: string;
            /**
             * @description Навыки студента
             * @example Python, FastAPI, PostgreSQL
             */
            skills?: string | null;
        };
        StudentUpdateRequest: {
            /** @description Новое имя студента */
            first_name?: string;
            /** @description Новая фамилия студента */
            last_name?: string;
            /** @description Новый список навыков */
            skills?: string | null;
        };
        StudentListResponse: {
            items: components["schemas"]["StudentResponse"][];
            /** @example 100 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        ProjectResponse: {
            /**
             * @description Уникальный идентификатор проекта
             * @example 10
             */
            id: number;
            /**
             * @description Название проекта
             * @example Capacity Planning
             */
            name: string;
            /**
             * @description Описание проекта
             * @example Сервис для планирования загрузки студенческой команды
             */
            description?: string | null;
            /**
             * Format: date-time
             * @description Дата создания проекта
             * @example 2026-03-13T10:00:00Z
             */
            created_at: string;
            /**
             * @description ID владельца проекта
             * @example 1
             */
            owner_student_id: number;
        };
        ProjectCreateRequest: {
            /**
             * @description Название проекта
             * @example Capacity Planning
             */
            name: string;
            /** @description Описание проекта */
            description?: string | null;
        };
        ProjectUpdateRequest: {
            /** @description Новое название проекта */
            name?: string;
            /** @description Новое описание проекта */
            description?: string | null;
        };
        ProjectJoinRequest: {
            /**
             * @description ID проекта для вступления
             * @example 10
             */
            project_id: number;
        };
        ProjectListResponse: {
            items: components["schemas"]["ProjectResponse"][];
            /** @example 25 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        ProjectMemberResponse: {
            /**
             * @description Уникальный идентификатор участника проекта
             * @example 15
             */
            id: number;
            /**
             * @description ID проекта
             * @example 10
             */
            project_id: number;
            /**
             * @description ID студента
             * @example 2
             */
            student_id: number;
            /**
             * @description Роль участника в проекте
             * @example backend developer
             */
            role: string;
            /**
             * Format: date
             * @description Дата вступления в проект
             * @example 2026-03-13
             */
            join_date: string;
            /**
             * @description Является ли участник активным
             * @example true
             */
            is_active: boolean;
        };
        ProjectMemberCreateByProjectRequest: {
            /**
             * @description ID студента
             * @example 2
             */
            student_id: number;
            /**
             * @description Роль участника проекта
             * @example tester
             */
            role: string;
        };
        ProjectMemberUpdateRequest: {
            /** @description Новая роль участника проекта */
            role?: string;
            /** @description Новый статус активности участника */
            is_active?: boolean;
        };
        ProjectMemberListResponse: {
            items: components["schemas"]["ProjectMemberResponse"][];
            /** @example 12 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        TeamResponse: {
            /**
             * @description Уникальный идентификатор команды
             * @example 5
             */
            id: number;
            /**
             * @description ID проекта
             * @example 10
             */
            project_id: number;
            /**
             * @description Название команды
             * @example Backend Team
             */
            name: string;
            /**
             * @description Описание команды
             * @example Команда backend-разработки
             */
            description?: string | null;
        };
        TeamCreateByProjectRequest: {
            /**
             * @description Название команды
             * @example Frontend Team
             */
            name: string;
            /** @description Описание команды */
            description?: string | null;
        };
        TeamUpdateRequest: {
            /** @description Новое название команды */
            name?: string;
            /** @description Новое описание команды */
            description?: string | null;
        };
        TeamListResponse: {
            items: components["schemas"]["TeamResponse"][];
            /** @example 6 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        TeamMembershipResponse: {
            /**
             * @description Уникальный идентификатор членства в команде
             * @example 30
             */
            id: number;
            /**
             * @description ID команды
             * @example 5
             */
            team_id: number;
            /**
             * @description ID участника проекта
             * @example 15
             */
            project_member_id: number;
            /**
             * @description Позиция участника в команде
             * @example team lead
             */
            position: string;
        };
        TeamMembershipCreateByTeamRequest: {
            /**
             * @description ID участника проекта
             * @example 15
             */
            project_member_id: number;
            /**
             * @description Позиция участника в команде
             * @example analyst
             */
            position: string;
        };
        TeamMembershipUpdateRequest: {
            /** @description Новая позиция участника в команде */
            position?: string;
        };
        TeamMembershipListResponse: {
            items: components["schemas"]["TeamMembershipResponse"][];
            /** @example 8 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        ErrorResponse: {
            error: {
                /**
                 * @description Машиночитаемый код ошибки
                 * @example STUDENT_NOT_FOUND
                 */
                code: string;
                /**
                 * @description Человекочитаемое описание ошибки
                 * @example Student with id=1 not found
                 */
                message: string;
                /** @description Дополнительная информация об ошибке */
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        BadRequestErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        UnauthorizedErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        ForbiddenErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        NotFoundErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        ConflictErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        InternalServerErrorResponse: components["schemas"]["ErrorResponse"] & Record<string, never>;
        ValidationErrorResponse: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Request validation failed */
                message: string;
                fields?: {
                    [key: string]: string[];
                };
            };
        };
        SprintResponse: {
            /**
             * @description Уникальный идентификатор спринта
             * @example 1
             */
            id: number;
            /**
             * @description ID проекта
             * @example 10
             */
            project_id: number;
            /**
             * @description Название спринта
             * @example Sprint 1
             */
            name: string;
            /**
             * Format: date
             * @description Дата начала спринта
             */
            start_date: string;
            /**
             * Format: date
             * @description Дата окончания спринта
             */
            end_date: string;
            /**
             * Format: date-time
             * @description Дата создания спринта
             */
            created_at: string;
        };
        SprintCreateRequest: {
            /** @description Название спринта */
            name: string;
            /**
             * Format: date
             * @description Дата начала спринта
             */
            start_date: string;
            /**
             * Format: date
             * @description Дата окончания спринта
             */
            end_date: string;
        };
        SprintListResponse: {
            items: components["schemas"]["SprintResponse"][];
            /** @example 5 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        ProjectTaskResponse: {
            /**
             * @description Уникальный идентификатор задачи
             * @example 7
             */
            id: number;
            /**
             * @description ID проекта
             * @example 10
             */
            project_id: number;
            /**
             * @description ID спринта
             * @example 2
             */
            sprint_id?: number | null;
            /**
             * @description Название задачи
             * @example Реализовать Swagger API
             */
            title: string;
            /** @description Описание задачи */
            description?: string | null;
            status: components["schemas"]["TaskStatus"];
            /** @enum {integer} */
            priority: 1 | 2 | 3 | 4 | 5;
            /**
             * Format: date-time
             * @description Дата создания задачи
             */
            created_at: string;
        };
        ProjectTaskCreateRequest: {
            /** @description ID спринта */
            sprint_id?: number | null;
            /** @description Название задачи */
            title: string;
            /** @description Описание задачи */
            description?: string | null;
            status: components["schemas"]["TaskStatus"];
            /** @enum {integer} */
            priority: 1 | 2 | 3 | 4 | 5;
        };
        ProjectTaskListResponse: {
            items: components["schemas"]["ProjectTaskResponse"][];
            /** @example 12 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        TaskAssignmentResponse: {
            /**
             * @description Уникальный идентификатор назначения задачи
             * @example 15
             */
            id: number;
            /** @description ID задачи */
            project_task_id: number;
            /** @description ID участника проекта */
            project_member_id: number;
            /**
             * Format: date-time
             * @description Дата назначения задачи
             */
            assigned_at: string;
            /** @enum {string} */
            state: "assigned" | "accepted" | "rejected" | "completed";
            /**
             * Format: date-time
             * @description Дата принятия задачи участником
             */
            accepted_at?: string | null;
        };
        TaskAssignmentCreateRequest: {
            /** @description ID участника проекта */
            project_member_id: number;
        };
        BusySlotResponse: {
            /**
             * @description Уникальный идентификатор слота занятости
             * @example 21
             */
            id: number;
            /** @description ID студента */
            student_id: number;
            /**
             * @description Тип слота занятости
             * @example lesson
             */
            slot_type: string;
            /**
             * Format: date-time
             * @description Начало слота занятости
             */
            start_datetime: string;
            /**
             * Format: date-time
             * @description Конец слота занятости
             */
            end_datetime: string;
            /** @description Описание события */
            description?: string | null;
            /**
             * Format: date-time
             * @description Дата создания слота
             */
            created_at: string;
            /** @description ID назначения задачи */
            task_assignment_id?: number | null;
        };
        BusySlotCreateRequest: {
            /** @description Тип слота занятости */
            slot_type: string;
            /** Format: date-time */
            start_datetime: string;
            /** Format: date-time */
            end_datetime: string;
            description?: string | null;
            task_assignment_id?: number | null;
        };
        TaskChangeRequestResponse: {
            /**
             * @description Уникальный идентификатор запроса
             * @example 4
             */
            id: number;
            /** @description ID назначения задачи */
            task_assignment_id: number;
            /** @description ID пользователя, создавшего запрос */
            requested_by_id: number;
            /** @description Причина запроса */
            reason: string;
            /**
             * @description Статус запроса
             * @example pending
             */
            status: string;
            /**
             * Format: date-time
             * @description Дата создания запроса
             */
            created_at: string;
            /** @description ID пользователя, обработавшего запрос */
            handled_by_id?: number | null;
            /**
             * Format: date-time
             * @description Дата обработки запроса
             */
            handled_at?: string | null;
        };
        TaskChangeRequestCreateRequest: {
            /** @description ID назначения задачи */
            task_assignment_id: number;
            /** @description ID пользователя */
            requested_by_id: number;
            /** @description Причина запроса */
            reason: string;
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BadRequestErrorResponse"];
            };
        };
        /** @description Требуется авторизация */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnauthorizedErrorResponse"];
            };
        };
        /** @description Отсутствуют права доступа для выполнения запроса */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ForbiddenErrorResponse"];
            };
        };
        /** @description Сущность не найдена */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NotFoundErrorResponse"];
            };
        };
        /** @description Конфликт данных */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConflictErrorResponse"];
            };
        };
        /** @description Ошибка валидации входных данных */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Внутренняя ошибка сервера */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InternalServerErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Номер страницы */
        Page: number;
        /** @description Количество элементов на странице */
        PageSize: number;
        /** @description ID студента */
        StudentId: number;
        /** @description ID проекта */
        ProjectId: number;
        /** @description ID команды */
        TeamId: number;
        /** @description ID задачи */
        TaskId: number;
        /** @description Фильтр по email */
        StudentEmailFilter: string;
        /** @description Фильтр по имени */
        StudentFirstNameFilter: string;
        /** @description Фильтр по фамилии */
        StudentLastNameFilter: string;
        /** @description Фильтр по навыкам */
        StudentSkillsFilter: string;
        /** @description Фильтр по названию проекта */
        ProjectNameFilter: string;
        /** @description Фильтр по ID владельца проекта */
        ProjectOwnerStudentIdFilter: number;
        /** @description Нижняя граница даты создания проекта */
        ProjectCreatedFromFilter: string;
        /** @description Верхняя граница даты создания проекта */
        ProjectCreatedToFilter: string;
        /** @description Фильтр по ID студента */
        ProjectMemberStudentIdFilter: number;
        /** @description Фильтр по роли участника проекта */
        ProjectMemberRoleFilter: string;
        /** @description Фильтр по активности участника проекта */
        ProjectMemberIsActiveFilter: boolean;
        /** @description Нижняя граница даты вступления в проект */
        ProjectMemberJoinDateFromFilter: string;
        /** @description Верхняя граница даты вступления в проект */
        ProjectMemberJoinDateToFilter: string;
        /** @description ID спринта */
        SprintId: number;
        /** @description ID участника проекта */
        ProjectMemberId: number;
        /** @description ID слота занятости */
        BusySlotId: number;
        /** @description ID запроса на изменение задачи */
        RequestId: number;
    };
    requestBodies: {
        StudentUpdateBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdateRequest"];
            };
        };
        ProjectCreateBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        ProjectUpdateBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        ProjectJoinBody: {
            content: {
                "application/json": components["schemas"]["ProjectJoinRequest"];
            };
        };
        ProjectMemberCreateByProjectBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberCreateByProjectRequest"];
            };
        };
        ProjectMemberUpdateByProjectBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberUpdateRequest"];
            };
        };
        TeamCreateByProjectBody: {
            content: {
                "application/json": components["schemas"]["TeamCreateByProjectRequest"];
            };
        };
        TeamUpdateBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        TeamMembershipCreateByTeamBody: {
            content: {
                "application/json": components["schemas"]["TeamMembershipCreateByTeamRequest"];
            };
        };
        TeamMembershipUpdateBody: {
            content: {
                "application/json": components["schemas"]["TeamMembershipUpdateRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
